# Generated by Django 5.1.5 on 2025-01-17 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='max_students',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
