# Generated by Django 5.1.5 on 2025-01-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_enrollments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollments',
            options={},
        ),
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_enrollment'),
        ),
    ]
